// Fixed interface text. Candidate answers and evaluator explanations are never translated here.
export const REPORT_LABEL_KEYS = ['report', 'id', 'copy', 'back', 'pdf', 'info', 'role', 'date', 'score', 'scale', 'summary', 'coverage', 'evidence', 'language', 'competencies', 'weight', 'behaviors', 'gaps', 'strengths', 'traceable', 'questions', 'question', 'response', 'followup', 'followResponse', 'rationale', 'ideal', 'metrics', 'metricsNote', 'duration', 'latency', 'words', 'exchanges', 'plan', 'actions', 'outcome', 'checklist', 'recommendation', 'record', 'page', 'of', 'unrated', 'sufficient', 'partial', 'insufficient', 'notAssessed', 'needsImprovement', 'developing', 'competent', 'strong', 'exceptional'] as const;
export type ReportLabelKey = typeof REPORT_LABEL_KEYS[number];
export type ReportLabels = Record<ReportLabelKey, string>;

const rows: Record<string, string> = {
 'en-US': 'Interview Evaluation Report|Assessment ID|Copy Assessment ID|Back to Dashboard|Save as PDF|Assessment Info|Target Role|Assessment Date|Overall Score|Performance Scale|Performance Summary|Assessment Coverage|Evidence|Language|Competency Analysis|Weight|Observable Behaviors|Gaps|Strengths|Traceable Evidence|Question Analysis|Question|Candidate Response|Follow-up Question|Follow-up Response|Scoring Rationale|Example of a Complete Answer|Session Metrics|Descriptive metrics; do not affect the score|Total Duration|Average Answer Latency|Word Count|Recorded Exchanges|7-Day Practice Plan|Actions|Expected Outcome|Action Checklist|Performance Recommendation|Assessment Record|Page|of|Unrated|Sufficient|Partial|Insufficient|Not Directly Assessed|Needs Improvement|Developing|Meets Standard|Strong|Exceptional',
 'ar-SA': 'تقرير تقييم المقابلة|رقم التقييم|نسخ رقم التقييم|العودة للوحة التحكم|حفظ PDF|معلومات التقييم|الوظيفة المستهدفة|تاريخ التقييم|التقييم الإجمالي|مقياس الأداء|ملخص الأداء|تغطية التقييم|الأدلة|اللغة|تحليل المهارات|الوزن|السلوكيات الملحوظة|نقاط التحسين|نقاط القوة|الأدلة الموثقة|تحليل الأسئلة|السؤال|إجابة المرشح|سؤال متابعة|إجابة المتابعة|سبب الدرجة|مثال لإجابة مكتملة|مؤشرات الجلسة|مؤشرات وصفية لا تؤثر على الدرجة|المدة الإجمالية|متوسط وقت بدء الإجابة|عدد الكلمات|المناقشات المسجلة|خطة تدريب لمدة 7 أيام|الإجراءات|النتيجة المتوقعة|قائمة الإجراءات|توصية الأداء|سجل التقييم|صفحة|من|غير قابل للتقييم|كافية|جزئية|غير كافية|لم تُقيّم مباشرة|يحتاج إلى تحسين|قيد التطوير|يحقق المستوى المطلوب|قوي|متميز',
 'ar-EG': 'تقرير تقييم الانترفيو|رقم التقييم|انسخ رقم التقييم|ارجع للوحة التحكم|احفظ PDF|معلومات التقييم|الوظيفة المطلوبة|تاريخ التقييم|التقييم الإجمالي|مقياس الأداء|ملخص الأداء|تغطية التقييم|الأدلة|اللغة|تحليل المهارات|الوزن|السلوكيات الملحوظة|نقط التحسين|نقط القوة|الأدلة الموثقة|تحليل الأسئلة|السؤال|إجابة المتقدم|سؤال متابعة|إجابة المتابعة|سبب الدرجة|مثال لإجابة كاملة|مؤشرات الجلسة|مؤشرات وصفية مش بتأثر على الدرجة|المدة الإجمالية|متوسط وقت بداية الإجابة|عدد الكلمات|المناقشات المسجلة|خطة تدريب لمدة 7 أيام|الخطوات|النتيجة المتوقعة|قائمة الخطوات|توصية الأداء|سجل التقييم|صفحة|من|مش قابل للتقييم|كافية|جزئية|مش كافية|ما اتقيّمتش مباشرة|محتاج تحسين|بيتطور|محقق المستوى المطلوب|قوي|متميز',
 'es-ES': 'Informe de evaluación de la entrevista|ID de evaluación|Copiar ID de evaluación|Volver al panel|Guardar como PDF|Información de evaluación|Puesto objetivo|Fecha de evaluación|Puntuación global|Escala de rendimiento|Resumen de rendimiento|Cobertura de evaluación|Evidencia|Idioma|Análisis de competencias|Peso|Conductas observadas|Áreas de mejora|Fortalezas|Evidencia verificable|Análisis de preguntas|Pregunta|Respuesta del candidato|Pregunta de seguimiento|Respuesta de seguimiento|Justificación de la puntuación|Ejemplo de respuesta completa|Métricas de la sesión|Métricas descriptivas; no afectan la puntuación|Duración total|Tiempo medio hasta responder|Número de palabras|Intercambios registrados|Plan de práctica de 7 días|Acciones|Resultado esperado|Lista de acciones|Recomendación de rendimiento|Registro de evaluación|Página|de|Sin evaluar|Suficiente|Parcial|Insuficiente|No evaluado directamente|Necesita mejorar|En desarrollo|Cumple el nivel esperado|Sólido|Excepcional',
 'fr-FR': 'Rapport d’évaluation de l’entretien|Identifiant de l’évaluation|Copier l’identifiant|Retour au tableau de bord|Enregistrer en PDF|Informations sur l’évaluation|Poste visé|Date de l’évaluation|Note globale|Échelle de performance|Résumé de la performance|Couverture de l’évaluation|Éléments probants|Langue|Analyse des compétences|Pondération|Comportements observés|Axes d’amélioration|Points forts|Éléments vérifiables|Analyse des questions|Question|Réponse du candidat|Question de suivi|Réponse de suivi|Justification de la note|Exemple de réponse complète|Indicateurs de la session|Indicateurs descriptifs sans effet sur la note|Durée totale|Délai moyen avant réponse|Nombre de mots|Échanges enregistrés|Plan d’entraînement de 7 jours|Actions|Résultat attendu|Liste des actions|Recommandation de performance|Dossier d’évaluation|Page|sur|Non évalué|Suffisants|Partiels|Insuffisants|Non évalué directement|À améliorer|En développement|Niveau attendu atteint|Solide|Exceptionnel',
 'de-DE': 'Bewertungsbericht zum Vorstellungsgespräch|Bewertungs-ID|Bewertungs-ID kopieren|Zurück zur Übersicht|Als PDF speichern|Bewertungsinformationen|Zielposition|Bewertungsdatum|Gesamtbewertung|Leistungsskala|Leistungsübersicht|Bewertungsabdeckung|Belege|Sprache|Kompetenzanalyse|Gewichtung|Beobachtetes Verhalten|Verbesserungsbereiche|Stärken|Nachprüfbare Belege|Fragenanalyse|Frage|Antwort der bewerbenden Person|Nachfrage|Antwort auf die Nachfrage|Bewertungsbegründung|Beispiel einer vollständigen Antwort|Sitzungskennzahlen|Beschreibende Kennzahlen ohne Einfluss auf die Bewertung|Gesamtdauer|Durchschnittliche Antwortverzögerung|Wortanzahl|Aufgezeichnete Gesprächswechsel|7-Tage-Übungsplan|Maßnahmen|Erwartetes Ergebnis|Maßnahmenliste|Leistungsempfehlung|Bewertungsprotokoll|Seite|von|Nicht bewertet|Ausreichend|Teilweise|Unzureichend|Nicht direkt bewertet|Verbesserungsbedarf|In Entwicklung|Erfüllt den Standard|Stark|Hervorragend',
 'it-IT': 'Rapporto di valutazione del colloquio|ID della valutazione|Copia ID della valutazione|Torna alla dashboard|Salva come PDF|Informazioni sulla valutazione|Ruolo desiderato|Data della valutazione|Punteggio complessivo|Scala di prestazione|Riepilogo della prestazione|Copertura della valutazione|Evidenze|Lingua|Analisi delle competenze|Peso|Comportamenti osservati|Aree di miglioramento|Punti di forza|Evidenze verificabili|Analisi delle domande|Domanda|Risposta del candidato|Domanda di approfondimento|Risposta di approfondimento|Motivazione del punteggio|Esempio di risposta completa|Metriche della sessione|Metriche descrittive senza effetto sul punteggio|Durata totale|Tempo medio prima della risposta|Numero di parole|Scambi registrati|Piano di pratica di 7 giorni|Azioni|Risultato atteso|Elenco delle azioni|Raccomandazione sulla prestazione|Registro della valutazione|Pagina|di|Non valutato|Sufficienti|Parziali|Insufficienti|Non valutato direttamente|Da migliorare|In sviluppo|Soddisfa lo standard|Solido|Eccezionale',
 'pt-BR': 'Relatório de avaliação da entrevista|ID da avaliação|Copiar ID da avaliação|Voltar ao painel|Salvar como PDF|Informações da avaliação|Cargo desejado|Data da avaliação|Nota geral|Escala de desempenho|Resumo do desempenho|Cobertura da avaliação|Evidências|Idioma|Análise de competências|Peso|Comportamentos observados|Pontos de melhoria|Pontos fortes|Evidências verificáveis|Análise das perguntas|Pergunta|Resposta do candidato|Pergunta de acompanhamento|Resposta de acompanhamento|Justificativa da nota|Exemplo de resposta completa|Métricas da sessão|Métricas descritivas sem efeito na nota|Duração total|Tempo médio até responder|Número de palavras|Interações registradas|Plano de prática de 7 dias|Ações|Resultado esperado|Lista de ações|Recomendação de desempenho|Registro da avaliação|Página|de|Não avaliado|Suficientes|Parciais|Insuficientes|Não avaliado diretamente|Precisa melhorar|Em desenvolvimento|Atende ao padrão|Forte|Excepcional',
 'zh-CN': '面试评估报告|评估编号|复制评估编号|返回控制面板|保存为PDF|评估信息|目标职位|评估日期|总评分|表现评分尺度|表现总结|评估覆盖率|证据|语言|能力分析|权重|观察到的行为|待改进之处|优点|可核实的证据|问题分析|问题|候选人回答|追问|追问回答|评分依据|完整回答示例|会话指标|描述性指标，不影响评分|总时长|平均回答等待时间|字词数|已记录的交流|7天练习计划|行动|预期成果|行动清单|表现建议|评估记录|页|共|未评分|充分|部分|不足|未直接评估|需要改进|发展中|达到标准|优秀|卓越',
 'ja-JP': '面接評価レポート|評価ID|評価IDをコピー|ダッシュボードに戻る|PDFとして保存|評価情報|志望職種|評価日|総合スコア|評価尺度|パフォーマンス概要|評価対象の網羅率|根拠|言語|能力分析|重み|観察された行動|改善点|強み|確認可能な根拠|質問分析|質問|応募者の回答|追加質問|追加質問への回答|採点理由|十分な回答の例|セッション指標|スコアに影響しない参考指標|合計時間|回答開始までの平均時間|単語数|記録されたやり取り|7日間の練習計画|取り組み|期待される成果|取り組み一覧|パフォーマンスへの提案|評価記録|ページ|全|未評価|十分|部分的|不十分|直接評価していない|改善が必要|成長途中|基準を満たす|優秀|卓越',
 'ko-KR': '면접 평가 보고서|평가 ID|평가 ID 복사|대시보드로 돌아가기|PDF로 저장|평가 정보|지원 직무|평가 날짜|종합 점수|성과 척도|성과 요약|평가 범위|근거|언어|역량 분석|가중치|관찰된 행동|개선점|강점|검증 가능한 근거|질문 분석|질문|지원자 답변|후속 질문|후속 답변|채점 근거|완전한 답변 예시|세션 지표|점수에 영향을 주지 않는 참고 지표|총 소요 시간|평균 답변 시작 시간|단어 수|기록된 대화|7일 연습 계획|실행 항목|기대 결과|실행 목록|성과 권고|평가 기록|페이지|전체|미평가|충분|부분적|불충분|직접 평가하지 않음|개선 필요|발전 중|기준 충족|우수|탁월',
 'hi-IN': 'साक्षात्कार मूल्यांकन रिपोर्ट|मूल्यांकन आईडी|मूल्यांकन आईडी कॉपी करें|डैशबोर्ड पर वापस जाएँ|PDF के रूप में सहेजें|मूल्यांकन जानकारी|लक्षित पद|मूल्यांकन तिथि|समग्र अंक|प्रदर्शन पैमाना|प्रदर्शन सारांश|मूल्यांकन कवरेज|प्रमाण|भाषा|कौशल विश्लेषण|भार|देखे गए व्यवहार|सुधार के क्षेत्र|मजबूत पक्ष|सत्यापन योग्य प्रमाण|प्रश्न विश्लेषण|प्रश्न|उम्मीदवार का उत्तर|अनुवर्ती प्रश्न|अनुवर्ती उत्तर|अंकों का कारण|पूर्ण उत्तर का उदाहरण|सत्र के आँकड़े|वर्णनात्मक आँकड़े; अंकों पर प्रभाव नहीं|कुल अवधि|उत्तर शुरू करने का औसत समय|शब्द संख्या|दर्ज संवाद|7 दिन की अभ्यास योजना|कार्य|अपेक्षित परिणाम|कार्य सूची|प्रदर्शन सुझाव|मूल्यांकन रिकॉर्ड|पृष्ठ|में से|मूल्यांकित नहीं|पर्याप्त|आंशिक|अपर्याप्त|सीधे मूल्यांकित नहीं|सुधार की आवश्यकता|विकासशील|मानक पूरा करता है|मजबूत|उत्कृष्ट',
 'tr-TR': 'Mülakat değerlendirme raporu|Değerlendirme kimliği|Değerlendirme kimliğini kopyala|Panele dön|PDF olarak kaydet|Değerlendirme bilgileri|Hedef pozisyon|Değerlendirme tarihi|Genel puan|Performans ölçeği|Performans özeti|Değerlendirme kapsamı|Kanıt|Dil|Yetkinlik analizi|Ağırlık|Gözlenen davranışlar|Gelişim alanları|Güçlü yönler|Doğrulanabilir kanıt|Soru analizi|Soru|Adayın yanıtı|Takip sorusu|Takip yanıtı|Puan gerekçesi|Eksiksiz yanıt örneği|Oturum ölçümleri|Puanı etkilemeyen betimleyici ölçümler|Toplam süre|Ortalama yanıt başlama süresi|Kelime sayısı|Kaydedilen konuşmalar|7 günlük çalışma planı|Eylemler|Beklenen sonuç|Eylem listesi|Performans önerisi|Değerlendirme kaydı|Sayfa|toplam|Puanlanmadı|Yeterli|Kısmi|Yetersiz|Doğrudan değerlendirilmedi|Geliştirilmesi gerekiyor|Gelişiyor|Standardı karşılıyor|Güçlü|Olağanüstü',
 'nl-NL': 'Beoordelingsrapport sollicitatiegesprek|Beoordelings-ID|Beoordelings-ID kopiëren|Terug naar dashboard|Opslaan als PDF|Beoordelingsinformatie|Beoogde functie|Beoordelingsdatum|Totaalscore|Prestatieschaal|Prestatieoverzicht|Beoordelingsdekking|Bewijs|Taal|Competentieanalyse|Gewicht|Waargenomen gedrag|Verbeterpunten|Sterke punten|Verifieerbaar bewijs|Vraaganalyse|Vraag|Antwoord van de kandidaat|Vervolgvraag|Vervolgantwoord|Scoreonderbouwing|Voorbeeld van een volledig antwoord|Sessiegegevens|Beschrijvende gegevens zonder invloed op de score|Totale duur|Gemiddelde tijd tot antwoord|Aantal woorden|Vastgelegde gesprekken|Oefenplan van 7 dagen|Acties|Verwacht resultaat|Actielijst|Prestatieadvies|Beoordelingsverslag|Pagina|van|Niet beoordeeld|Voldoende|Gedeeltelijk|Onvoldoende|Niet rechtstreeks beoordeeld|Verbetering nodig|In ontwikkeling|Voldoet aan de norm|Sterk|Uitstekend',
 'ru-RU': 'Отчёт об оценке собеседования|Идентификатор оценки|Копировать идентификатор|Вернуться на панель|Сохранить как PDF|Сведения об оценке|Целевая должность|Дата оценки|Общий балл|Шкала результатов|Итоги выступления|Охват оценки|Подтверждения|Язык|Анализ компетенций|Вес|Наблюдаемое поведение|Области улучшения|Сильные стороны|Проверяемые подтверждения|Анализ вопросов|Вопрос|Ответ кандидата|Дополнительный вопрос|Ответ на дополнительный вопрос|Обоснование балла|Пример полного ответа|Показатели сессии|Описательные показатели не влияют на балл|Общая длительность|Среднее время до начала ответа|Количество слов|Записанные обмены репликами|План практики на 7 дней|Действия|Ожидаемый результат|Список действий|Рекомендация по результатам|Запись оценки|Страница|из|Без оценки|Достаточные|Частичные|Недостаточные|Не оценивалось напрямую|Требует улучшения|Развивается|Соответствует стандарту|Сильный уровень|Выдающийся уровень',
 'id-ID': 'Laporan evaluasi wawancara|ID evaluasi|Salin ID evaluasi|Kembali ke dasbor|Simpan sebagai PDF|Informasi evaluasi|Posisi tujuan|Tanggal evaluasi|Skor keseluruhan|Skala kinerja|Ringkasan kinerja|Cakupan evaluasi|Bukti|Bahasa|Analisis kompetensi|Bobot|Perilaku yang diamati|Area perbaikan|Kekuatan|Bukti yang dapat diverifikasi|Analisis pertanyaan|Pertanyaan|Jawaban kandidat|Pertanyaan lanjutan|Jawaban lanjutan|Alasan penilaian|Contoh jawaban lengkap|Metrik sesi|Metrik deskriptif; tidak memengaruhi skor|Durasi total|Rata-rata waktu mulai menjawab|Jumlah kata|Percakapan tercatat|Rencana latihan 7 hari|Tindakan|Hasil yang diharapkan|Daftar tindakan|Rekomendasi kinerja|Catatan evaluasi|Halaman|dari|Belum dinilai|Memadai|Sebagian|Tidak memadai|Tidak dinilai langsung|Perlu perbaikan|Berkembang|Memenuhi standar|Kuat|Luar biasa',
 'fil-PH': 'Ulat ng pagsusuri sa panayam|ID ng pagsusuri|Kopyahin ang ID|Bumalik sa dashboard|I-save bilang PDF|Impormasyon ng pagsusuri|Target na posisyon|Petsa ng pagsusuri|Kabuuang marka|Sukatan ng pagganap|Buod ng pagganap|Saklaw ng pagsusuri|Ebidensya|Wika|Pagsusuri ng mga kakayahan|Bigat|Naobserbahang asal|Mga dapat pagbutihin|Mga kalakasan|Napapatunayang ebidensya|Pagsusuri ng mga tanong|Tanong|Sagot ng kandidato|Karagdagang tanong|Karagdagang sagot|Paliwanag ng marka|Halimbawa ng kumpletong sagot|Mga sukatan ng sesyon|Mga sukatan na hindi nakaaapekto sa marka|Kabuuang tagal|Karaniwang oras bago sumagot|Bilang ng mga salita|Naitalang palitan|7 araw na plano ng pagsasanay|Mga hakbang|Inaasahang resulta|Listahan ng mga hakbang|Rekomendasyon sa pagganap|Tala ng pagsusuri|Pahina|sa|Hindi namarkahan|Sapat|Bahagya|Hindi sapat|Hindi direktang nasuri|Kailangang pagbutihin|Umuunlad|Pasok sa pamantayan|Mahusay|Natatangi',
 'pl-PL': 'Raport oceny rozmowy kwalifikacyjnej|Identyfikator oceny|Kopiuj identyfikator oceny|Powrót do panelu|Zapisz jako PDF|Informacje o ocenie|Docelowe stanowisko|Data oceny|Ocena ogólna|Skala wyników|Podsumowanie wyników|Zakres oceny|Dowody|Język|Analiza kompetencji|Waga|Zaobserwowane zachowania|Obszary poprawy|Mocne strony|Weryfikowalne dowody|Analiza pytań|Pytanie|Odpowiedź kandydata|Pytanie uzupełniające|Odpowiedź uzupełniająca|Uzasadnienie oceny|Przykład pełnej odpowiedzi|Wskaźniki sesji|Wskaźniki opisowe bez wpływu na ocenę|Łączny czas|Średni czas do rozpoczęcia odpowiedzi|Liczba słów|Zarejestrowane wymiany|7-dniowy plan ćwiczeń|Działania|Oczekiwany wynik|Lista działań|Rekomendacja dotycząca wyników|Zapis oceny|Strona|z|Nieocenione|Wystarczające|Częściowe|Niewystarczające|Nie oceniono bezpośrednio|Wymaga poprawy|W rozwoju|Spełnia standard|Mocny poziom|Wyjątkowy poziom',
 'sv-SE': 'Utvärderingsrapport för intervjun|Utvärderings-ID|Kopiera utvärderings-ID|Tillbaka till översikten|Spara som PDF|Utvärderingsinformation|Målroll|Utvärderingsdatum|Totalpoäng|Prestationsskala|Prestationsöversikt|Utvärderingens täckning|Belägg|Språk|Kompetensanalys|Vikt|Observerade beteenden|Förbättringsområden|Styrkor|Verifierbara belägg|Frågeanalys|Fråga|Kandidatens svar|Följdfråga|Svar på följdfråga|Poängmotivering|Exempel på ett fullständigt svar|Sessionsmått|Beskrivande mått utan påverkan på poängen|Total tid|Genomsnittlig tid till svar|Antal ord|Registrerade samtalsutbyten|7 dagars övningsplan|Åtgärder|Förväntat resultat|Åtgärdslista|Prestationsrekommendation|Utvärderingsprotokoll|Sida|av|Ej bedömd|Tillräckliga|Delvisa|Otillräckliga|Inte direkt bedömd|Behöver förbättras|Under utveckling|Uppfyller standarden|Stark|Enastående',
 'bg-BG': 'Доклад за оценка на интервюто|Идентификатор на оценката|Копирай идентификатора|Назад към таблото|Запази като PDF|Информация за оценката|Целева длъжност|Дата на оценката|Обща оценка|Скала на представяне|Обобщение на представянето|Обхват на оценката|Доказателства|Език|Анализ на компетенциите|Тежест|Наблюдавано поведение|Области за подобрение|Силни страни|Проверими доказателства|Анализ на въпросите|Въпрос|Отговор на кандидата|Допълнителен въпрос|Допълнителен отговор|Обосновка на оценката|Пример за пълен отговор|Показатели на сесията|Описателни показатели без влияние върху оценката|Обща продължителност|Средно време до отговор|Брой думи|Записани обмени|7-дневен план за упражнения|Действия|Очакван резултат|Списък с действия|Препоръка за представянето|Запис на оценката|Страница|от|Без оценка|Достатъчни|Частични|Недостатъчни|Не е оценено пряко|Нуждае се от подобрение|В развитие|Покрива стандарта|Силно|Изключително',
 'ro-RO': 'Raport de evaluare a interviului|ID-ul evaluării|Copiază ID-ul evaluării|Înapoi la panou|Salvează ca PDF|Informații despre evaluare|Rol vizat|Data evaluării|Scor general|Scală de performanță|Rezumatul performanței|Acoperirea evaluării|Dovezi|Limbă|Analiza competențelor|Pondere|Comportamente observate|Aspecte de îmbunătățit|Puncte forte|Dovezi verificabile|Analiza întrebărilor|Întrebare|Răspunsul candidatului|Întrebare suplimentară|Răspuns suplimentar|Justificarea scorului|Exemplu de răspuns complet|Indicatorii sesiunii|Indicatori descriptivi fără efect asupra scorului|Durată totală|Timp mediu până la răspuns|Număr de cuvinte|Schimburi înregistrate|Plan de practică de 7 zile|Acțiuni|Rezultat așteptat|Lista acțiunilor|Recomandare privind performanța|Înregistrarea evaluării|Pagina|din|Neevaluat|Suficiente|Parțiale|Insuficiente|Neevaluat direct|Necesită îmbunătățire|În dezvoltare|Îndeplinește standardul|Puternic|Excepțional',
 'cs-CZ': 'Zpráva o hodnocení pohovoru|ID hodnocení|Kopírovat ID hodnocení|Zpět na přehled|Uložit jako PDF|Informace o hodnocení|Cílová pozice|Datum hodnocení|Celkové skóre|Stupnice výkonu|Shrnutí výkonu|Pokrytí hodnocení|Důkazy|Jazyk|Analýza kompetencí|Váha|Pozorované chování|Oblasti ke zlepšení|Silné stránky|Ověřitelné důkazy|Analýza otázek|Otázka|Odpověď kandidáta|Doplňující otázka|Doplňující odpověď|Zdůvodnění skóre|Příklad úplné odpovědi|Ukazatele relace|Popisné ukazatele bez vlivu na skóre|Celková doba|Průměrná doba do odpovědi|Počet slov|Zaznamenané výměny|7denní plán procvičování|Kroky|Očekávaný výsledek|Seznam kroků|Doporučení k výkonu|Záznam hodnocení|Strana|z|Nehodnoceno|Dostatečné|Částečné|Nedostatečné|Přímo nehodnoceno|Vyžaduje zlepšení|Ve vývoji|Splňuje standard|Silný výkon|Výjimečný výkon',
 'el-GR': 'Έκθεση αξιολόγησης συνέντευξης|Κωδικός αξιολόγησης|Αντιγραφή κωδικού|Επιστροφή στον πίνακα|Αποθήκευση ως PDF|Πληροφορίες αξιολόγησης|Στοχευόμενη θέση|Ημερομηνία αξιολόγησης|Συνολική βαθμολογία|Κλίμακα απόδοσης|Σύνοψη απόδοσης|Κάλυψη αξιολόγησης|Στοιχεία|Γλώσσα|Ανάλυση δεξιοτήτων|Βαρύτητα|Παρατηρούμενες συμπεριφορές|Πεδία βελτίωσης|Δυνατά σημεία|Επαληθεύσιμα στοιχεία|Ανάλυση ερωτήσεων|Ερώτηση|Απάντηση υποψηφίου|Συμπληρωματική ερώτηση|Συμπληρωματική απάντηση|Αιτιολόγηση βαθμολογίας|Παράδειγμα πλήρους απάντησης|Μετρήσεις συνεδρίας|Περιγραφικές μετρήσεις χωρίς επίδραση στη βαθμολογία|Συνολική διάρκεια|Μέσος χρόνος μέχρι την απάντηση|Αριθμός λέξεων|Καταγεγραμμένες ανταλλαγές|Πρόγραμμα εξάσκησης 7 ημερών|Ενέργειες|Αναμενόμενο αποτέλεσμα|Λίστα ενεργειών|Σύσταση απόδοσης|Αρχείο αξιολόγησης|Σελίδα|από|Χωρίς βαθμολογία|Επαρκή|Μερικά|Ανεπαρκή|Δεν αξιολογήθηκε άμεσα|Χρειάζεται βελτίωση|Σε ανάπτυξη|Καλύπτει το πρότυπο|Ισχυρή απόδοση|Εξαιρετική απόδοση',
 'fi-FI': 'Haastattelun arviointiraportti|Arvioinnin tunnus|Kopioi arvioinnin tunnus|Takaisin koontinäyttöön|Tallenna PDF-muodossa|Arvioinnin tiedot|Tavoiteltu tehtävä|Arviointipäivä|Kokonaispisteet|Suoritusasteikko|Suorituksen yhteenveto|Arvioinnin kattavuus|Näyttö|Kieli|Osaamisanalyysi|Paino|Havaitut toimintatavat|Kehityskohteet|Vahvuudet|Todennettava näyttö|Kysymysten analyysi|Kysymys|Hakijan vastaus|Jatkokysymys|Jatkovastaus|Pisteytyksen perustelu|Esimerkki täydellisestä vastauksesta|Istunnon mittarit|Kuvailevat mittarit eivät vaikuta pisteisiin|Kokonaiskesto|Keskimääräinen vastausviive|Sanamäärä|Tallennetut keskusteluvuorot|7 päivän harjoittelusuunnitelma|Toimet|Odotettu tulos|Toimintalista|Suoritussuositus|Arviointitietue|Sivu|/|Ei arvioitu|Riittävä|Osittainen|Riittämätön|Ei arvioitu suoraan|Vaatii parannusta|Kehittyvä|Täyttää vaatimukset|Vahva|Poikkeuksellinen',
 'hr-HR': 'Izvještaj o procjeni intervjua|ID procjene|Kopiraj ID procjene|Povratak na nadzornu ploču|Spremi kao PDF|Informacije o procjeni|Ciljana pozicija|Datum procjene|Ukupna ocjena|Ljestvica uspješnosti|Sažetak uspješnosti|Obuhvat procjene|Dokazi|Jezik|Analiza kompetencija|Težina|Uočena ponašanja|Područja za poboljšanje|Prednosti|Provjerljivi dokazi|Analiza pitanja|Pitanje|Odgovor kandidata|Dodatno pitanje|Dodatni odgovor|Obrazloženje ocjene|Primjer potpunog odgovora|Pokazatelji sesije|Opisni pokazatelji ne utječu na ocjenu|Ukupno trajanje|Prosječno vrijeme do odgovora|Broj riječi|Zabilježene razmjene|7-dnevni plan vježbanja|Aktivnosti|Očekivani ishod|Popis aktivnosti|Preporuka za uspješnost|Zapis procjene|Stranica|od|Nije ocijenjeno|Dostatni|Djelomični|Nedostatni|Nije izravno procijenjeno|Potrebno poboljšanje|U razvoju|Zadovoljava standard|Snažno|Iznimno',
 'ms-MY': 'Laporan penilaian temu duga|ID penilaian|Salin ID penilaian|Kembali ke papan pemuka|Simpan sebagai PDF|Maklumat penilaian|Jawatan sasaran|Tarikh penilaian|Skor keseluruhan|Skala prestasi|Ringkasan prestasi|Liputan penilaian|Bukti|Bahasa|Analisis kompetensi|Pemberat|Tingkah laku diperhatikan|Aspek penambahbaikan|Kekuatan|Bukti yang boleh disahkan|Analisis soalan|Soalan|Jawapan calon|Soalan susulan|Jawapan susulan|Rasional pemarkahan|Contoh jawapan lengkap|Metrik sesi|Metrik deskriptif tanpa kesan pada skor|Jumlah tempoh|Purata masa sebelum menjawab|Bilangan perkataan|Pertukaran direkodkan|Pelan latihan 7 hari|Tindakan|Hasil dijangka|Senarai tindakan|Cadangan prestasi|Rekod penilaian|Halaman|daripada|Tidak dinilai|Mencukupi|Sebahagian|Tidak mencukupi|Tidak dinilai secara langsung|Perlu penambahbaikan|Sedang berkembang|Memenuhi piawaian|Kukuh|Cemerlang',
 'sk-SK': 'Správa o hodnotení pohovoru|ID hodnotenia|Kopírovať ID hodnotenia|Späť na prehľad|Uložiť ako PDF|Informácie o hodnotení|Cieľová pozícia|Dátum hodnotenia|Celkové skóre|Stupnica výkonu|Zhrnutie výkonu|Pokrytie hodnotenia|Dôkazy|Jazyk|Analýza kompetencií|Váha|Pozorované správanie|Oblasti na zlepšenie|Silné stránky|Overiteľné dôkazy|Analýza otázok|Otázka|Odpoveď kandidáta|Doplňujúca otázka|Doplňujúca odpoveď|Zdôvodnenie skóre|Príklad úplnej odpovede|Ukazovatele relácie|Opisné ukazovatele bez vplyvu na skóre|Celkové trvanie|Priemerný čas do odpovede|Počet slov|Zaznamenané výmeny|7-dňový plán precvičovania|Kroky|Očakávaný výsledok|Zoznam krokov|Odporúčanie k výkonu|Záznam hodnotenia|Strana|z|Nehodnotené|Dostatočné|Čiastočné|Nedostatočné|Priamo nehodnotené|Vyžaduje zlepšenie|Vo vývoji|Spĺňa štandard|Silný výkon|Výnimočný výkon',
 'da-DK': 'Vurderingsrapport for interviewet|Vurderings-ID|Kopiér vurderings-ID|Tilbage til oversigten|Gem som PDF|Vurderingsoplysninger|Ønsket stilling|Vurderingsdato|Samlet score|Præstationsskala|Præstationsoversigt|Vurderingsdækning|Belæg|Sprog|Kompetenceanalyse|Vægt|Observeret adfærd|Forbedringsområder|Styrker|Verificerbare belæg|Spørgsmålsanalyse|Spørgsmål|Kandidatens svar|Opfølgende spørgsmål|Opfølgende svar|Begrundelse for score|Eksempel på et fuldstændigt svar|Sessionsmålinger|Beskrivende målinger uden indflydelse på scoren|Samlet varighed|Gennemsnitlig tid til svar|Antal ord|Registrerede udvekslinger|7-dages øvelsesplan|Handlinger|Forventet resultat|Handlingsliste|Præstationsanbefaling|Vurderingsjournal|Side|af|Ikke bedømt|Tilstrækkelige|Delvise|Utilstrækkelige|Ikke direkte vurderet|Kræver forbedring|Under udvikling|Opfylder standarden|Stærk|Fremragende',
 'ta-IN': 'நேர்காணல் மதிப்பீட்டு அறிக்கை|மதிப்பீட்டு அடையாள எண்|மதிப்பீட்டு எண்ணை நகலெடு|முகப்புப் பலகைக்குத் திரும்பு|PDF ஆகச் சேமி|மதிப்பீட்டு விவரங்கள்|இலக்கு வேலை|மதிப்பீட்டுத் தேதி|ஒட்டுமொத்த மதிப்பெண்|செயல்திறன் அளவுகோல்|செயல்திறன் சுருக்கம்|மதிப்பீட்டு உள்ளடக்கம்|ஆதாரங்கள்|மொழி|திறன் பகுப்பாய்வு|எடை|கவனிக்கப்பட்ட நடத்தைகள்|மேம்படுத்த வேண்டியவை|பலங்கள்|சரிபார்க்கக்கூடிய ஆதாரங்கள்|கேள்விகளின் பகுப்பாய்வு|கேள்வி|விண்ணப்பதாரரின் பதில்|தொடர்க் கேள்வி|தொடர்ப் பதில்|மதிப்பெண்ணின் காரணம்|முழுமையான பதிலின் எடுத்துக்காட்டு|அமர்வு அளவீடுகள்|மதிப்பெண்ணைப் பாதிக்காத விளக்க அளவீடுகள்|மொத்த நேரம்|பதில் தொடங்கும் சராசரி நேரம்|சொற்களின் எண்ணிக்கை|பதிவுசெய்யப்பட்ட உரையாடல்கள்|7 நாள் பயிற்சித் திட்டம்|செயல்கள்|எதிர்பார்க்கப்படும் விளைவு|செயல் பட்டியல்|செயல்திறன் பரிந்துரை|மதிப்பீட்டுப் பதிவு|பக்கம்|மொத்தம்|மதிப்பிடப்படவில்லை|போதுமானவை|பகுதியளவு|போதாதவை|நேரடியாக மதிப்பிடப்படவில்லை|மேம்பாடு தேவை|வளர்ந்து வருகிறது|தரநிலையை அடைகிறது|வலுவானது|மிகச் சிறந்தது',
 'uk-UA': 'Звіт про оцінювання співбесіди|Ідентифікатор оцінювання|Копіювати ідентифікатор|Повернутися до панелі|Зберегти як PDF|Інформація про оцінювання|Цільова посада|Дата оцінювання|Загальний бал|Шкала результатів|Підсумок результатів|Охоплення оцінювання|Підтвердження|Мова|Аналіз компетенцій|Вага|Спостережувана поведінка|Напрями покращення|Сильні сторони|Перевірювані підтвердження|Аналіз запитань|Запитання|Відповідь кандидата|Додаткове запитання|Додаткова відповідь|Обґрунтування бала|Приклад повної відповіді|Показники сесії|Описові показники не впливають на бал|Загальна тривалість|Середній час до відповіді|Кількість слів|Записані обміни|План практики на 7 днів|Дії|Очікуваний результат|Список дій|Рекомендація за результатами|Запис оцінювання|Сторінка|з|Без оцінки|Достатні|Часткові|Недостатні|Не оцінювалося безпосередньо|Потребує покращення|Розвивається|Відповідає стандарту|Сильний рівень|Винятковий рівень'
};

const catalog = Object.fromEntries(Object.entries(rows).map(([language, row]) => {
 const values = row.split('|');
 if (values.length !== REPORT_LABEL_KEYS.length || values.some(value => !value.trim())) throw new Error(`Incomplete report labels: ${language}`);
 return [language, Object.fromEntries(REPORT_LABEL_KEYS.map((key, index) => [key, values[index]])) as ReportLabels];
})) as Record<string, ReportLabels>;

export function getReportLabels(language: string, webMock: boolean): ReportLabels {
 return catalog[webMock ? language : 'en-US'] || catalog['en-US'];
}

export function reportStatusLabel(value: string, labels: ReportLabels): string {
 const keys: Record<string, ReportLabelKey> = {
  'Sufficient': 'sufficient', 'Partial': 'partial', 'Insufficient': 'insufficient', 'Not Directly Assessed': 'notAssessed',
  'Needs Improvement': 'needsImprovement', 'Developing': 'developing', 'Competent / Meets Standard': 'competent',
  'Strong': 'strong', 'Strong Performance': 'strong', 'Exceptional': 'exceptional', 'Distinguished': 'exceptional', 'Insufficient Evidence': 'insufficient', 'Unrated (Insufficient Evidence)': 'unrated',
 };
 return keys[value] ? labels[keys[value]] : value;
}

const metadataKeys = ['Role-Specific', 'Behavioral', 'Technical', 'Project Deep Dive', 'Beginner', 'Intermediate', 'Expert', 'General'];
const metadataRows: Record<string, string> = {
 'en-US': 'Role-Specific|Behavioral|Technical|Project Deep Dive|Beginner|Intermediate|Expert|General',
 'ar-SA': 'خاص بالوظيفة|سلوكي|تقني|مناقشة مشروع بالتفصيل|مبتدئ|متوسط|خبير|عام',
 'ar-EG': 'خاص بالوظيفة|سلوكي|تقني|مناقشة مشروع بالتفصيل|مبتدئ|متوسط|خبير|عام',
 'es-ES': 'Específico del puesto|Conductual|Técnico|Análisis detallado de un proyecto|Principiante|Intermedio|Experto|General',
 'fr-FR': 'Spécifique au poste|Comportemental|Technique|Analyse approfondie d’un projet|Débutant|Intermédiaire|Expert|Général',
 'de-DE': 'Positionsbezogen|Verhaltensbezogen|Technisch|Vertiefte Projektanalyse|Anfänger|Fortgeschritten|Experte|Allgemein',
 'it-IT': 'Specifico per il ruolo|Comportamentale|Tecnico|Analisi approfondita del progetto|Principiante|Intermedio|Esperto|Generale',
 'pt-BR': 'Específico do cargo|Comportamental|Técnico|Análise aprofundada de projeto|Iniciante|Intermediário|Especialista|Geral',
 'zh-CN': '职位专项|行为面试|技术面试|项目深入分析|初级|中级|专家|综合',
 'ja-JP': '職種別|行動面接|技術面接|プロジェクトの詳細分析|初級|中級|上級|一般',
 'ko-KR': '직무별|행동 면접|기술 면접|프로젝트 심층 분석|초급|중급|전문가|일반',
 'hi-IN': 'पद-विशिष्ट|व्यवहार संबंधी|तकनीकी|परियोजना का गहन विश्लेषण|शुरुआती|मध्यम|विशेषज्ञ|सामान्य',
 'tr-TR': 'Pozisyona özel|Davranışsal|Teknik|Ayrıntılı proje incelemesi|Başlangıç|Orta|Uzman|Genel',
 'nl-NL': 'Functiespecifiek|Gedragsgericht|Technisch|Diepgaande projectanalyse|Beginner|Gemiddeld|Expert|Algemeen',
 'ru-RU': 'По должности|Поведенческое|Техническое|Подробный разбор проекта|Начальный|Средний|Экспертный|Общее',
 'id-ID': 'Khusus posisi|Perilaku|Teknis|Analisis proyek mendalam|Pemula|Menengah|Ahli|Umum',
 'fil-PH': 'Tiyak sa posisyon|Pag-uugali|Teknikal|Masusing pagsusuri ng proyekto|Baguhan|Katamtaman|Dalubhasa|Pangkalahatan',
 'pl-PL': 'Specyficzne dla stanowiska|Behawioralne|Techniczne|Dogłębna analiza projektu|Początkujący|Średnio zaawansowany|Ekspercki|Ogólne',
 'sv-SE': 'Rollspecifik|Beteendeinriktad|Teknisk|Fördjupad projektanalys|Nybörjare|Medelnivå|Expert|Allmän',
 'bg-BG': 'Според длъжността|Поведенческо|Техническо|Подробен анализ на проект|Начално|Средно|Експертно|Общо',
 'ro-RO': 'Specific rolului|Comportamental|Tehnic|Analiză aprofundată a proiectului|Începător|Intermediar|Expert|General',
 'cs-CZ': 'Specifické pro pozici|Behaviorální|Technické|Hloubková analýza projektu|Začátečník|Středně pokročilý|Expert|Obecné',
 'el-GR': 'Ειδικό για τη θέση|Συμπεριφορικό|Τεχνικό|Εις βάθος ανάλυση έργου|Αρχάριος|Ενδιάμεσος|Ειδικός|Γενικό',
 'fi-FI': 'Tehtäväkohtainen|Käyttäytymiseen liittyvä|Tekninen|Projektin syväanalyysi|Aloittelija|Keskitaso|Asiantuntija|Yleinen',
 'hr-HR': 'Specifično za poziciju|Bihevioralno|Tehničko|Detaljna analiza projekta|Početnik|Srednji|Stručnjak|Opće',
 'ms-MY': 'Khusus jawatan|Tingkah laku|Teknikal|Analisis projek mendalam|Pemula|Pertengahan|Pakar|Umum',
 'sk-SK': 'Špecifické pre pozíciu|Behaviorálne|Technické|Hĺbková analýza projektu|Začiatočník|Stredne pokročilý|Expert|Všeobecné',
 'da-DK': 'Stillingsspecifik|Adfærdsbaseret|Teknisk|Dybdegående projektanalyse|Begynder|Mellem|Ekspert|Generel',
 'ta-IN': 'வேலைக்கேற்றது|நடத்தை சார்ந்தது|தொழில்நுட்பம்|திட்டத்தின் விரிவான பகுப்பாய்வு|தொடக்கநிலை|இடைநிலை|நிபுணர்|பொது',
 'uk-UA': 'За посадою|Поведінкове|Технічне|Докладний аналіз проєкту|Початковий|Середній|Експертний|Загальне',
};

export function reportMetadataLabel(value: string, language: string, webMock: boolean): string {
 const index = metadataKeys.indexOf(value);
 if (!webMock || index < 0) return value;
 return (metadataRows[language] || metadataRows['en-US']).split('|')[index];
}

export function reportTime(value: number | null | undefined, unit: 'minute' | 'second', language: string, webMock: boolean): string {
 if (typeof value !== 'number' || !Number.isFinite(value)) return '—';
 if (!webMock) return `${value}${unit === 'minute' ? 'm' : 's'}`;
 return new Intl.NumberFormat(language, { style: 'unit', unit, unitDisplay: 'short', maximumFractionDigits: 1 }).format(value);
}
